apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-secret
  labels:
    app: mysql
    {{- include "mysql.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-root-password: "NTdRcVplaDBRaw=="
  mysql-password: "NUg4WldVTFV0cQ=="