apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}-nginx-configmap
  labels:
    app: tokyo
    service: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
data:
  default.conf : |-
    server {
      listen 80 default_server;
      server_name localhost;

      root /project/public;

      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options "nosniff";

      index index.php index.html;

      charset utf-8;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location = /favicon.ico { access_log off; log_not_found off; }
      location = /robots.txt  { access_log off; log_not_found off; }

      error_page 404 /index.php;

      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }

      location ~ /\.(?!well-known).* {
          deny all;
      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}-phpfpm-configmap
  labels:
    app: tokyo
    service: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
data:
  www.conf : |-
    [www]

    user = www-data
    group = www-data

    listen = /var/run/php-fpm.sock

    pm = dynamic
    pm.max_children = 5
    pm.start_servers = 2
    pm.min_spare_servers = 1
    pm.max_spare_servers = 3