apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}-deployment
  labels:
    app: tokyo
    service: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tokyo
      service: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: tokyo
        service: {{ .Values.serviceName }}
    spec:
      nodeSelector:
        node: slave
      containers:
      - name: {{ .Values.serviceName }}
        image: "{{ .Values.imageRepository }}/{{ .Values.serviceName }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: 9000
        volumeMounts:
          - name: env
            mountPath: /project
            readOnly: true
          - name: phpfpm
            mountPath: /usr/local/etc/php-fpm.d
            readOnly: true
      - name: nginx
        image: nginx:mainline-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginxconf
            mountPath: /etc/nginx/conf.d
            readOnly: true
      imagePullSecrets:
        - name: tokyo-image-pull-secret
      volumes:
        - name: nginxconf
          configMap:
            name: {{ .Values.serviceName }}-nginx-configmap
            items:
              - key: default.conf
                path: default.conf
        - name: env
          configMap:
            name: {{ .Values.serviceName }}-env-configmap
            items:
              - key: .env
                path: .env
        - name: phpfpm
          configMap:
            name: {{ .Values.serviceName }}-phpfpm-configmap
            items:
              - key: www.conf
                path: www.conf