apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-ecr-secret
  labels:
    app: tokyo
    service: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: |-
    {{ .Files.Get "config.json" | b64enc }}
type: kubernetes.io/dockerconfigjson