apiVersion: v1
kind: Secret
metadata:
  name: dronesecret
  labels:
    app: drone
  namespace: default
data:
  DRONE_GITHUB_CLIENT_ID: OTFiNzA1N2EzZmFkMmI0ZmQ5NGE=
  DRONE_GITHUB_CLIENT_SECRET: ZjllN2NmMDQyNTYxN2EyMWIzMGIyYTYyMjBhNmMwZWFkODRiNDU3OQ==
  DRONE_RPC_SECRET: YmVhMjZhMjIyMWZkbm1jZDBlYTM4NzJzY2M0NDVlY2E2
  DRONE_RUNNER_AGENT_USER: ZHJvbmVCdWlsZGVy
  DRONE_RUNNER_AGENT_PASS: RXg4M3p6SnUxa0NVMTI3aDBWRHpDTTJhTHBJMDBSbEk=
  DRONE_RUNNER_AGENT_PUBK: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDMU9WRnorSDVoOUpBT0RJT3FHZk5HMDZQRGtOL2VrM3VmNWQyeGhKUGdZeTNqOTMzSys5bzB0SSsvYllQTjdDbGZjbFpLaHliVUZqTHNRRGtjbHlORjkxTVNaYm9BNzlhWTNFeHJQZXprUDA5T0I2MmcvaXRyb1k3SkdZdUFWT2h6enZHOVdjQVV3SEhlWXdQeEl4QnJEMVIyY2h0dXRiY3F5V0VlQjliZDVQdGRuZ2xEVFFKZDE4enFMK0JuL3RvS1ltWG10MUt2UWY0eDE4V3NhdHZ0VFFPVXV3UVV3dEwyS25tbUZrRFhFeXh5SkJidE9SdVUyak9SU0ZxSkpDZ3N3UmRrNmtFMWZxdHZicnArTFltU0FlRloveTUvako4c0VyV3pjWDRSbnJsSWxPYzVkRlAzN20xK1BvNkxVSzZOYlVxQ1VBVGJhN3ZQL1BvQ2NxelQgZHJvbmVCdWlsZGVyQGp1bXBib3gK