apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: tokyo-{{ .Values.serviceName }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.serviceName }}
              servicePort: 80
            path: "/{{ .Values.namespace }}(/|$)(.*)"
  tls:
      - hosts:
          - {{ .Values.host }}
        secretName: {{ .Values.host }}-tls