apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: tokyo
    service: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tokyo
    service: {{ .Values.serviceName }}
  ports:
  - port: 80
    targetPort: 80
